#!/bin/csh
#PBS -l ncpus=32
#ncpus must be a multiple of 16
#PBS -l walltime=1:00
#PBS -j oe
#PBS -q batch
set echo
#move to my $SCRATCH directory
cd $SCRATCH
#copy executable to $SCRATCH
cp $HOME/hello .
#run my executable
setenv OMP_NUM_THREADS 16
omplace -nt $OMP_NUM_THREADS ./hello
