engine: phys.cpp main.cpp mather.h sphere.cpp shape.cpp sphere.h phys.h shape.h commonFunctions.h commonFunctions.cpp cube.h cube.cpp world.h world.cpp
	g++ -o engine.exe phys.cpp main.cpp sphere.cpp shape.cpp commonFunctions.cpp cube.cpp world.cpp -lGL -lGLU -lglut
