engine: phys.cpp main.cpp mather.h sphere.cpp draw.h shape.cpp sphere.h phys.h shape.h commonFunctions.h commonFunctions.cpp
	g++ -o engine.exe phys.cpp main.cpp sphere.cpp shape.cpp commonFunctions.cpp -lGL -lGLU -lglut
