#!/bin/sh
# Format: 
# time ./nbody.exec totalTimeSteps secondsPerStep stepsPerOutput progress? results? parallel? N

# default serial
# time ./nbody.exec 1000 10000 1 0 0 0 N

# default parallel
time ./nbody.exec 1000 10000 1 0 0 1 240

