#!/bin/bash

#PBS -A eecs587f14_flux
#PBS -l qos=flux
#PBS -q flux
#PBS -l nodes=16
#PBS -l walltime=00:01:00

module load gcc/4.8.0
module load openmpi/1.8.2/gcc/4.8.0

cd /home/bijan/bf-eecs587/HW/3
pwd
(time mpirun -pernode ./hello 2000 2.0 100) 2> roughTime.txt 1> roughOutput.txt
