#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -N v5
#PBS -j oe
#PBS -o $JOB_ID.err
#PBS -l walltime=00:15:00

module load openmpi/1.4.3-intel
cd $PBS_OWORKDIR
make
export OMP_NUM_THREADS = 8
(time ./alexandrian 850) 2> timeResults.txt 1> alexNumbers.txt
