#!/bin/bash

#PBS -A eecs587f14_flux
#PBS -l qos=flux
#PBS -q flux
#PBS -l nodes=1
#PBS -l walltime=00:05:10
#PBS -e output_1000_1.txt

module purge
module load gcc/4.8.0
module load openmpi/1.8.2/gcc/4.8.0

cd /home/bijan/bf-eecs587/HW/3
pwd
mpirun ./hello 1000 500 
